kind: Service
apiVersion: v1
metadata:
  name: articulate-frontend
spec:
  selector:
    app: articulate
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: articulate
spec:
  selector:
      matchLabels:
        app: articulate
  replicas: 3
  template:
    metadata:
      labels:
        app: articulate
    spec:
      containers:
        - name: articulate
          image: kanwaljitkhurmi/mb3:articulateLatest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: myregistrykey